### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/Blender-Modular-tree-addon#30]
Let's try to get this thing runnin' fast! Here is a brief performance report of the create_tree function:

Using 15 branch iterations on my MacBook Pro
Processor: 2.5 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3

```
create_tree took 2.5 seconds
    uv took 1.4 seconds
    armature took 1.0 seconds
```

I added reports for the "major" parts of the create_tree function with *reasonable* settings (these are not accurate reports, but they certainly give the big picture). Clearly, the uv and armature creation is what's having the biggest impact on performance.

**Comment by ekaj2** [comment]
Using 30 branch iterations on the same computer:

```
create_tree took 2475.069555044174 seconds
    uv took 2412.7697792053223 seconds
    armature took 56.6273090839386 seconds
```

So I think that the armature is okay for now, but the uv adding **definitely** needs some work...

**Comment by MaximeHerpin** [comment]
I think the only thing that can really be improved is the uv part, as the armature complexity is due to the automatic weighting, which is inevitable.

I have made some graphs, the uv operator seems to be linear with the face count, but very unpredictably with the seams count and positions. The rotate function is also linear with the number of faces.

However, the number of faces is roughly  A*(1+p)^n where A is a constant, p is the branching probability and n the number of iterations; so all functions in the UV operator are exponential with the iterations.

The best way to improve it would be to create our own unwrapping function, but even tho it would be linear with the face count, and doing so would need the tree creation process to be changed, as I think the mesh itself would have to be created at the beginning; that means there is no way to know if it will be faster in advance.

**Comment by ekaj2** [comment]
Turns out the uv time is mostly due to the one line:

`bpy.ops.uv.unwrap(method='ANGLE_BASED', margin=0.001)`

(and is therefore not able to be optimized much at all from our end)

So it turns out that the weighted armature and the unwrap are the "bottlenecks" and are not really even part of the addon.

The good news:
This issue can be closed

The bad news:
The performance can't really be improved much at all.

**Comment by MaximeHerpin** [comment]
Maybe there is no need to unwrap the whole tree, I guess that using the generated coordinates for small branches wouldn't be too obvious, so the trees could be unwrapped for the first n iterations, and a vertex color data would switch to generated for the remaining iterations.

I will implement that.
